### ISSUE TITLE
Path Prefix

### ISSUE THREAD

**Issue by smartforcedev** [RealFaviconGenerator/grunt-real-favicon#15]
Nice Plugin! Thx!
It would be nice if there was an option to prefix the "icons_path" variable. Maybe there is another way to insert something like "<?php print $somepath; ?>" in front of the "icons_path"?

**Comment by phbernard** [comment]
Wow, the plugin was just revived. Sorry for the late answer.

Unfortunately this is not as simple as it sounds. Sure, we could use PHP (or another template language) in the `icons_path`. As this path is normally injected in HTML file, we would take care to do so in PHP files so the path is eventually processed by mod_php or something similar. But this is not the only place where the path is used: it is also present in files such as `browserconfig.xml` (for Windows tiles) and `manifest.json` (for Android Chrome). And unlike regular HTML page such as `index.php`, these files are normally not processed by PHP. Suddenly, a simple problem turns out to be quite annoying: maybe we can rename `browserconfig.xml` to `browserconfig.xml.php` (but this solution is for PHP only; we wanted to support anything), maybe we can configure the web server to process this file in particular...

I need to sleep on this one :)

**Comment by FStop** [comment]
We we're having this issue with a WordPress theme (not using the plugin because of reasons) and solved this issue with a [grunt-shell](https://github.com/sindresorhus/grunt-shell) task:

```
shell: {
	favicons_post: {
		command: [
			"sed -i '' 's/<?php echo esc_url( get_template_directory_uri() ); ?>/\\\\\\\/\\\\\\\/yourdomain.com\\\\\\\/wp-content\\\\\\\/themes\\\\\\\/your-theme\\\\\\\//' assets/images/favicons/manifest.json",
			"sed -i '' 's/<?php echo esc_url( get_template_directory_uri() ); ?>/\\\/\\\/yourdomain.com\\\/wp-content\\\/themes\\\/your-theme\\\//' assets/images/favicons/browserconfig.xml"
		].join( ' && ' )
	}
}
```

which replaces the dynamic PHP path with a hard coded (protocol-relative) URL to the favicons. Not super elegant, but it does the trick.

**Comment by phbernard** [comment]
Thank you for the workaround. This is a bit similar employed in the [Rails plugin](https://github.com/RealFaviconGenerator/rails_real_favicon/blob/master/lib/generators/favicon_generator.rb): it uses a special key as the path (`Dfv87ZbNh2`) so it gets a very specific string it can safely search and replace.

So many backslashes... I think I hate sed more than I love it :) I particularly like the fact that `manifest.json` gets more backslashes than `browserconfig.xml` (this is because backslash is a special char in JSON and not in XML, am I right?), which makes these two lines asymmetrical and even more awkward.

I entered https://github.com/RealFaviconGenerator/rfg-api/issues/6 . Having a generic helper for this makes sense after all. But I won't work on it any soon, so your workaround definitely makes sense.

**Comment by markcarver** [comment]
Just chiming in here because I do believe this is needed.

In my case (using Drupal/Twig), I need to create a fully qualified URL to this asset based on the theme that's using it:

```twig
{{ file_url(theme.path ~ '/favicons/apple-touch-icon-57x57.png') }}
```

I understand having to deal with multiple platforms/unique cases. I think in this case, it would simply make more sense to allow a simple callback. If the plugin detects that it's a function, it simply passes it to the generator, i.e.:
```js
iconPath: function (filename) {
  return "{{ file_url(theme.path ~ '/favicons/" + filename + "') }}";
}
```

This is likely the least intrusive and most permissive way to handle this kind of "necessity" when dealing with complex platforms.

**Comment by markcarver** [comment]
Turns out it's not a simple as "passing it to the generator" (which is server side) since you can't pass functions via an HTTP request 😃 

Instead, the only option is to "post process" the code returned from the server. This can be accomplished by overriding the "path" with a special prefix that will get replaced later in the callback(s).

See #33 for the PR

**Comment by markcarver** [comment]
P.P.S, if you're in dire need to use this (until an official release can be made), you can simply require the following:

```bash
npm install grunt-real-favicon@https://github.com/markcarver/grunt-real-favicon/archive/patch-1.tar.gz --save-dev
```

**Comment by markcarver** [comment]
Did a little more work on this (realized that `browserconfig.xml` and `manifest.json` needed to be handled as well. See PR (#34) for working example.
